version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432 # Insert this with your .env file
      - DB_USER=postgres # Insert this with your .env file
      - DB_PASSWORD=postgres # Insert this with your .env file
      - DB_NAME=restaurant # Insert this with your .env file
      - SERVER_PORT=8080
    depends_on:
      - postgres
    volumes:
      - ./configs:/app/configs

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres # Insert this with your .env file
      - POSTGRES_PASSWORD=postgres # Insert this with your .env file
      - POSTGRES_DB=restaurant # Insert this with your .env file
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: